name: reservation-system
namespace: erlendum

replicaCount: 1

image:
  repository: erlendum/rsoi-lab-02-reservation-system
  tag: latest

postgresql:
  dsn: ""

services:
  library-system: ""
  rating-system: ""
  reservation-system: ""

port: 80