name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  test-gateway:
    name: Test gateway
    uses: ./.github/workflows/test-service.yml
    with:
      service-name: gateway

  test-library-system:
    name: Test library-system
    uses: ./.github/workflows/test-service.yml
    with:
      service-name: library-system

  test-rating-system:
    name: Test rating-system
    uses: ./.github/workflows/test-service.yml
    with:
      service-name: rating-system

  test-reservation-system:
    name: Test reservation-system
    uses: ./.github/workflows/test-service.yml
    with:
      service-name: reservation-system

  build-gateway:
    name: Build gateway
    needs: ["test-gateway"]
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: gateway
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-library-system:
    name: Build library-system
    needs: ["test-library-system"]
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: library-system
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-rating-system:
    name: Build rating-system
    needs: ["test-rating-system"]
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: rating-system
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-reservation-system:
    name: Build reservation-system
    needs: ["test-reservation-system"]
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: reservation-system
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-gateway:
    name: Deploy gateway
    needs: ["build-gateway"]
    uses: ./.github/workflows/deploy-service.yml
    with:
      service-name: gateway
    secrets:
      POSTGRESQL_DSN: ""
      KUBECONFIG: ${{ secrets.KUBECONFIG }}

  deploy-library-system:
    name: Deploy library-system
    needs: ["build-library-system"]
    uses: ./.github/workflows/deploy-service.yml
    with:
      service-name: library-system
    secrets:
      POSTGRESQL_DSN: ${{ secrets.LIBRARY_SYSTEM_POSTGRESQL_DSN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}

  deploy-rating-system:
    name: Deploy rating-system
    needs: ["build-rating-system"]
    uses: ./.github/workflows/deploy-service.yml
    with:
      service-name: rating-system
    secrets:
      POSTGRESQL_DSN: ${{ secrets.RATING_SYSTEM_POSTGRESQL_DSN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      
  deploy-reservation-system:
    name: Deploy reservation-system
    needs: ["build-reservation-system"]
    uses: ./.github/workflows/deploy-service.yml
    with:
      service-name: reservation-system
    secrets:
      POSTGRESQL_DSN: ${{ secrets.RESERVATION_SYSTEM_POSTGRESQL_DSN }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      
  autograding:
    name: Autograding
    needs: ["deploy-gateway","deploy-reservation-system","deploy-library-system","deploy-rating-system"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]' 

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true
